[project]
name = "sharp-core"
version = "0.1.0"
description = "Core HTTP client and shared utilities for Sharp IoT devices"
requires-python = ">=3.13"
authors = [
    { name = "Jakub Fijałkowski" }
]
dependencies = [
    "requests>=2.31.0",
]